apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config.yaml
  - workloads.yaml
  - schedules.yaml
  - ingress.yaml
  - network-policies.yaml
  - alerts.yaml
